-- MySQL Script generated by MySQL Workbench
-- Fri Nov  3 11:40:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema auditoria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auditoria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auditoria` DEFAULT CHARACTER SET utf8 ;
USE `auditoria` ;

-- -----------------------------------------------------
-- Table `auditoria`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT '1',
  `token` VARCHAR(100) NOT NULL,
  `remember_token` VARCHAR(100) NULL,
  `role` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria`.`business` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(100) NOT NULL DEFAULT 'business_default.png',
  `folio` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria`.`users_has_business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria`.`users_has_business` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `business_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_users_has_business_business1_idx` (`business_id` ASC),
  INDEX `fk_users_has_business_users_idx` (`user_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_has_business_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `auditoria`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_business_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `auditoria`.`business` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria`.`departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `aka` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `user_id` INT NOT NULL,
  `business_id` INT NOT NULL,
  `updated_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departments_business1_idx` (`business_id` ASC),
  INDEX `fk_departments_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_departments_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `auditoria`.`business` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `auditoria`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria`.`audits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria`.`audits` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria`.`questions` (
  `id` INT NOT NULL,
  `question` VARCHAR(255) NOT NULL,
  `type` VARCHAR(45) NOT NULL DEFAULT 'optinal',
  `opc1` VARCHAR(100) NULL,
  `opc2` VARCHAR(100) NULL,
  `opc3` VARCHAR(100) NULL,
  `correct` VARCHAR(100) NULL,
  `comment` VARCHAR(255) NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `audit_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_audits1_idx` (`audit_id` ASC),
  CONSTRAINT `fk_questions_audits1`
    FOREIGN KEY (`audit_id`)
    REFERENCES `auditoria`.`audits` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `auditoria`.`audits_has_departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auditoria`.`audits_has_departments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `audit_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  `business_id` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_audits_has_departments_departments1_idx` (`department_id` ASC),
  INDEX `fk_audits_has_departments_audits1_idx` (`audit_id` ASC),
  INDEX `fk_audits_has_departments_business1_idx` (`business_id` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_audits_has_departments_audits1`
    FOREIGN KEY (`audit_id`)
    REFERENCES `auditoria`.`audits` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audits_has_departments_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `auditoria`.`departments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audits_has_departments_business1`
    FOREIGN KEY (`business_id`)
    REFERENCES `auditoria`.`business` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

START TRANSACTION;
USE `auditoria`;
INSERT INTO `auditoria`.`users` (`id`, `username`, `password`, `active`, `token`, `remember_token`, `role`, `created_at`, `updated_at`) VALUES (1, 'root@admin.com', '$2a$10$X8T4arjdknnCTN9FW78P/eq9wlcQuNsh1HYr5P.11Q9mh.YSo2ySi', DEFAULT, '122131', NULL, 'Administer', NULL, NULL);

COMMIT;
